/**
 * reports.js
 * EnergizeOS Commissioning Copilot V1
 *
 * ReportService — generates structured commissioning reports.
 *
 * Flow:
 *   report type → retrieval sweep over project documents
 *   → report-specific prompt → AiService → markdown report
 *   → preview / copy / download (.md)
 *
 * In mock mode (no API key) the service produces a real skeleton report
 * from templates + document inventory + missing-document analysis, so
 * the workflow is fully demonstrable without a key.
 */

"use strict";

class ReportService {
  /**
   * @param {object} deps { store, retrieval, ai }
   */
  constructor(deps) {
    this.store = deps.store;
    this.retrieval = deps.retrieval;
    this.ai = deps.ai;
  }

  /**
   * Generate a report.
   * @param {string} typeId   - from CxTemplates.REPORT_TYPES
   * @param {object} project  - { id, name, siteType }
   * @param {Array}  documents
   * @param {Array}  chatFindings - recent assistant messages (strings)
   * @returns {Promise<{markdown: string, mode: string}>}
   */
  async generate(typeId, project, documents, chatFindings = []) {
    const type = window.CxTemplates.REPORT_TYPES.find(t => t.id === typeId);
    if (!type) throw new Error("Unknown report type: " + typeId);

    // Retrieval sweep — pull the most relevant chunks for this report type
    const query = this._sweepQuery(typeId);
    const retrieval = await this.retrieval.retrieve(query, project.id, { topK: 12 });

    const header = this._header(type, project, documents);

    if (!this.ai.isLive) {
      return { markdown: header + this._mockBody(typeId, project, documents, retrieval), mode: "mock" };
    }

    const prompt = this._prompt(typeId, type, project, documents, chatFindings);
    const result = await this.ai.ask(prompt, { project, documents, retrieval });
    return { markdown: header + result.text, mode: result.mode };
  }

  // ---------------------------------------------------------------- helpers

  _sweepQuery(typeId) {
    const queries = {
      "summary":      "commissioning status test results complete pass fail alarm issue",
      "open-issues":  "issue defect deviation fail open pending TBD missing blocked alarm fault",
      "risk":         "risk hazard warning missing TBD unconfirmed pending safety trip fault",
      "fat":          "FAT factory acceptance test IO modbus wiring checklist",
      "sat":          "SAT site acceptance test field verification witness interlock trip",
      "handoff":      "handoff settings versions training documents punch list complete",
      "troubleshoot": "fault alarm trip fail error symptom cause",
    };
    return queries[typeId] || "commissioning";
  }

  _header(type, project, documents) {
    const D = window.CxDomain;
    const docLines = documents.length
      ? documents.map(d => `- ${d.fileName} (${D.categoryLabel(d.category)})`).join("\n")
      : "- None uploaded";
    return `# ${type.label}

**Project:** ${project.name || "(unnamed)"}
**Site type:** ${D.siteTypeLabel(project.siteType)}
**Date:** ${new Date().toISOString().slice(0, 10)}
**Generated by:** EnergizeOS Commissioning Copilot V1

**Source documents:**
${docLines}

> ${D.SAFETY_DISCLAIMER}

---

`;
  }

  _prompt(typeId, type, project, documents, chatFindings) {
    const findings = chatFindings.length
      ? `\n\nFindings from this session's chat analysis (incorporate where relevant):\n${chatFindings.slice(-3).map(f => "- " + f.slice(0, 400)).join("\n")}`
      : "";

    const instructions = {
      "summary": "Generate a Commissioning Summary in markdown: ## System Description, ## Work Completed, ## Test Results, ## Findings, ## Risks, ## Open Questions, ## Recommended Next Actions. Base every project-specific claim on the retrieved excerpts and cite file names. Where information is missing, state it explicitly in Open Questions.",
      "open-issues": "Generate an Open Issues List in markdown as a table: | # | Issue | Evidence (file) | Severity | Recommended Action | Suggested Owner |. Extract issues from the retrieved excerpts (failures, deviations, TBDs, missing items, alarms). If few issues are found in documents, say so rather than inventing.",
      "risk": "Generate a Risk Register in markdown as a table: | # | Risk | Source Evidence | Severity (H/M/L) | Likelihood (H/M/L) | Mitigation | Owner |. Include document-gap risks (missing required documents) and any safety-relevant findings.",
      "fat": "Generate a project-tailored FAT Checklist in markdown, grouped by section with checkbox items (- [ ]). Start from the canonical EMS/BESS FAT structure in your system knowledge, then tailor items to the specific equipment named in the retrieved excerpts. Mark items that cannot be defined yet due to missing documents.",
      "sat": "Generate a project-tailored SAT Checklist in markdown, grouped by section with checkbox items (- [ ]). Include witnessed negative tests (each interlock forced FALSE blocks action) and trip-lockout verification. Tailor to equipment named in the retrieved excerpts.",
      "handoff": "Generate a Customer Handoff Report in markdown: ## Project Summary, ## Commissioning Scope Completed, ## Test Results Summary, ## As-Left Settings & Versions, ## Open Items, ## Operating Instructions Summary, ## O&M Recommendations, ## Contacts. Professional customer-facing tone. Flag every section where source data is missing.",
      "troubleshoot": "Generate a Troubleshooting Report in markdown using: ## Symptom, ## Evidence, ## Possible Causes (ranked), ## Checks Performed / Recommended, ## Recommended Action, ## Escalation Path. Base it on the chat findings and retrieved excerpts. If there is no active troubleshooting context, state that and provide the general intake structure instead.",
    };

    return `Generate the following report: ${type.label}.

${instructions[typeId]}${findings}

Output ONLY the report body in clean markdown (the header block is added separately). Do not include a title line.`;
  }

  /** Mock report body — real document inventory + gap analysis, no AI. */
  _mockBody(typeId, project, documents, retrieval) {
    const D = window.CxDomain;
    const required = D.COMMISSIONING_KNOWLEDGE.required_docs_by_site[project.siteType] || [];
    const have = new Set(documents.map(d => d.category));
    const missing = required.filter(c => !have.has(c));

    const excerpts = retrieval.slice(0, 5).map(r =>
      `- **${r.chunk.fileName}**${r.chunk.page ? ` p.${r.chunk.page}` : ""}: ${r.chunk.text.slice(0, 140).replace(/\s+/g, " ")}…`
    ).join("\n") || "- No relevant content retrieved.";

    return `**[MOCK MODE — configure an Anthropic API key in Settings to generate full AI-written reports. The document analysis below is real.]**

## Document Inventory Analysis
- Documents uploaded: ${documents.length}
- Recommended categories for ${D.siteTypeLabel(project.siteType)}: ${required.map(D.categoryLabel).join(", ") || "n/a"}
- **Missing recommended documents:** ${missing.length ? missing.map(D.categoryLabel).join(", ") : "none"}

## Most Relevant Retrieved Content
${excerpts}

## Next Step
Add an API key (Settings) and regenerate this report for full AI-written analysis with evidence citations.`;
  }

  /** Trigger a browser download of the markdown report. */
  download(markdown, project, typeLabel) {
    const safe = (s) => (s || "report").replace(/[^a-z0-9\-]+/gi, "-").toLowerCase();
    const fname = `${safe(project.name)}-${safe(typeLabel)}-${new Date().toISOString().slice(0, 10)}.md`;
    const blob = new Blob([markdown], { type: "text/markdown" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = fname;
    a.click();
    URL.revokeObjectURL(a.href);
  }
}

window.CxReports = { ReportService };
