function setK(id,v,c=''){const e=$(id);e.className='kpi '+c;e.querySelector('b').textContent=v;}
function update(){if(!started)return;const x=S.x,soc=x.bE?100*S.E/x.bE:0,saved=Math.max(0,S.baseFuel-S.fuel),re=S.loadE?100*S.reE/S.loadE:0;setK('kFuel',`${S.fuel.toFixed(0)} L`);setK('kSave',`${saved.toFixed(0)} L`,saved>0?'ok':'');setK('kRE',`${re.toFixed(1)}%`,re>35?'ok':'');setK('kCurt',`${S.curtE.toFixed(2)} MWh`,S.curtE>1?'warn':'');setK('kFreq',`${S.fmin.toFixed(2)}/${S.fmax.toFixed(2)}`,S.fmin<x.uf1||S.fmax>61.2?'bad':'ok');setK('kRo',`${S.rocof.toFixed(2)} Hz/s`,S.rocof>x.rocofTrip?'bad':'ok');setK('kSOC',`${soc.toFixed(1)}%`,soc<x.socLow*100||soc>x.socHigh*100?'warn':'ok');setK('kEENS',`${S.unservedE.toFixed(3)} MWh`,S.unservedE>0.01?'bad':'ok');$('bMode').textContent=S.op;$('bFreq').textContent=`${S.f.toFixed(3)} Hz`;$('bRun').textContent=ui;$('bRun').className='badge '+(ui==='RUNNING'?'ok':ui==='PAUSED'?'warn':'');$('pills').innerHTML=`<span class="pill ${S.n1?'ok':'bad'}">Gen N-1 ${S.n1?'OK':'FAIL'}</span><span class="pill ${Math.abs(S.f-x.f0)<.3?'ok':'bad'}">Δf ${(S.f-x.f0).toFixed(3)} Hz</span><span class="pill ${S.V>.9&&S.V<1.1?'ok':'bad'}">V ${S.V.toFixed(3)} pu</span><span class="pill">F10 ${S.fast10.toFixed(1)} MW</span><span class="pill">S60 ${S.spin60.toFixed(1)} MW</span><span class="pill">Start10 ${S.start10.toFixed(1)} MW</span><span class="pill ${Math.abs(S.residual)<.1?'ok':'bad'}">Residual ${S.residual.toFixed(3)} MW</span>`;updateSLD();updateButtons();}
function plot(id,keys,colors){const c=$(id),r=c.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);c.width=Math.max(2,r.width*dpr);c.height=Math.max(2,r.height*dpr);const g=c.getContext('2d'),w=c.width,h=c.height;g.fillStyle='#fff';g.fillRect(0,0,w,h);if(series.length<2)return;const ml=42*dpr,mr=10*dpr,mt=10*dpr,mb=18*dpr,t0=series[0].t,t1=series.at(-1).t,vals=keys.flatMap(k=>series.map(d=>d[k]));let mn=Math.min(...vals),mx=Math.max(...vals);if(mn===mx){mn-=1;mx+=1;}if(keys.includes('f')){mn=Math.min(mn,S.x.f0-.8);mx=Math.max(mx,S.x.f0+.8);}const X=t=>ml+(w-ml-mr)*(t-t0)/Math.max(1,t1-t0),Y=v=>mt+(h-mt-mb)*(1-(v-mn)/(mx-mn));g.strokeStyle='#E5E9EE';for(let i=0;i<5;i++){const y=mt+(h-mt-mb)*i/4;g.beginPath();g.moveTo(ml,y);g.lineTo(w-mr,y);g.stroke();}keys.forEach((k,j)=>{g.beginPath();series.forEach((d,i)=>{const xx=X(d.t),yy=Y(d[k]);i?g.lineTo(xx,yy):g.moveTo(xx,yy);});g.strokeStyle=colors[j];g.lineWidth=(j===0?2.1:1.5)*dpr;g.stroke();});}
function draw(){plot('pChart',['Sload','dg','pv','wind','b','grid'],['#64748B','#7C3AED','#D4840A','#0EA5E9','#16A34A','#8B5CF6']);plot('fChart',['f'],['#C026D3']);plot('vChart',['V'],['#B45309']);plot('qChart',['Q'],['#3B82F6']);}
function updateSLD(){const map={sldGrid:S.gridAvailable&&S.pccClosed,sldDG:S.fleet.some(g=>g.online),sldBESS:S.x.bP>0,sldPV:S.pv>0,sldWind:S.wind>0};for(const[k,v]of Object.entries(map))$(k).style.opacity=v?1:.2;$('sldText').textContent=`${S.op} · f ${S.f.toFixed(3)} Hz · V ${S.V.toFixed(3)} pu · SOC ${(S.x.bE?100*S.E/S.x.bE:0).toFixed(1)}%`;}
function setUI(s){ui=s;updateButtons();}
function updateButtons(){const start=$('start'),pause=$('pause'),reset=$('reset'),exp=$('export'),faults=[...document.querySelectorAll('[data-fault]')];start.disabled=ui==='RUNNING'||ui==='COMPLETE';pause.disabled=ui!=='RUNNING';exp.disabled=!started;start.textContent=ui==='PAUSED'&&started?'继续':ui==='RUNNING'?'运行中':ui==='COMPLETE'?'已完成':'启动';pause.textContent='暂停';start.className='btn '+((ui==='IDLE'||ui==='PAUSED')?'primary':'');pause.className='btn '+(ui==='RUNNING'?'primary':'');reset.className='btn '+(ui==='COMPLETE'?'primary':'');faults.forEach(b=>{const active=S.activeFaults?.has(b.dataset.fault);b.disabled=ui!=='RUNNING'||active;b.className='btn fault'+(active?' active':'');b.style.background=active?'#FEE2E2':'';});}
function loop(){if(ui!=='RUNNING')return;const n=Math.max(1,Math.round(8/S.x.dt));for(let i=0;i<n&&S.t<S.T&&ui==='RUNNING';i++)step();update();draw();if(S.t>=S.T){setUI('COMPLETE');log(`${ts(S.t)} simulation complete`);return;}raf=requestAnimationFrame(loop);}
function exportJSON(){if(!started)return;const out={modelVersion:VERSION,build:BUILD,generatedAt:new Date().toISOString(),scope:'Conceptual RMS-style screening only; not load-flow, short-circuit, EMT, protection coordination or detailed engineering.',inputs:S.x,mode,kpis:{fuel_L:S.fuel,fuelSavedBaseline_L:Math.max(0,S.baseFuel-S.fuel),renewableToLoad_pct:S.loadE?100*S.reE/S.loadE:0,curtailment_MWh:S.curtE,EENS_MWh:S.unservedE,fMin_Hz:S.fmin,fMax_Hz:S.fmax,rocofPeak_Hzs:S.rocof,Vmin_pu:S.vmin,Vmax_pu:S.vmax,finalSOC_pct:S.x.bE?100*S.E/S.x.bE:0,generationN1:S.n1,maxPowerResidual_MW:S.residualMax},events,timeseries:series};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:'application/json'}));a.download=`energize-mine-sim-v6-4-${Date.now()}.json`;a.click();}
function bind(){document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{if(ui==='RUNNING')return;document.querySelectorAll('.tab').forEach(q=>q.classList.remove('active'));t.classList.add('active');mode=t.dataset.mode;$('gridGroup').style.display=mode==='offgrid'?'none':'block';validate();});document.querySelectorAll('input,select').forEach(e=>e.addEventListener('change',()=>ui!=='RUNNING'&&validate()));$('start').onclick=()=>{if(!started&&!init())return;if(S.trip){log('请先重置后再启动');return;}setUI('RUNNING');cancelAnimationFrame(raf);loop();};$('pause').onclick=()=>{setUI('PAUSED');cancelAnimationFrame(raf);update();};$('reset').onclick=()=>{cancelAnimationFrame(raf);started=false;S={};series=[];events=[];setUI('IDLE');init();};$('export').onclick=exportJSON;document.querySelectorAll('[data-fault]').forEach(b=>b.onclick=()=>fault(b.dataset.fault));window.addEventListener('resize',()=>started&&draw());validate();updateButtons();}
document.addEventListener('DOMContentLoaded',bind);
