(()=>{
'use strict';
const VERSION='V6.1';
const BUILD='physics-correction-r1';
const $=id=>document.getElementById(id);
const num=id=>Number($(id)?.value||0);
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const lerp=(a,b,t)=>a+(b-a)*t;
const firstOrder=(y,u,tau,dt)=>y+(u-y)*clamp(dt/Math.max(tau,dt),0,1);
let mode='offgrid',ui='IDLE',running=false,started=false,raf=null,S={},series=[],events=[],seed=42;
function rng(){seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;}
function normal(){const u=Math.max(rng(),1e-9),v=Math.max(rng(),1e-9);return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v);}
function log(msg){const el=$('log');el.textContent+=`\n${msg}`;el.scrollTop=el.scrollHeight;}
function ts(t){const h=Math.floor(t/3600),m=Math.floor(t%3600/60),s=Math.floor(t%60);return`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;}
function input(){return{dt:num('dt')||.5,hours:num('hours')||24,f0:num('f0')||60,load:num('load')||12,loadVar:num('loadVar')||1.5,motorMW:num('motorMW')||2,motorInt:(num('motorInt')||45)*60,pvMax:num('pvMax'),cloud:num('cloud'),windMax:num('windMax'),windMean:num('windMean')||8,dg33:Math.round(num('dg33')),dg12:Math.round(num('dg12')),droop:(num('droop')||4)/100,minLoad:num('minLoad')||.35,rampUp:num('rampUp')||.2,rampDn:num('rampDn')||1,startDelay:num('startDelay')||600,bP:num('bP'),bE:num('bE'),soc0:num('soc0')/100,eta:Math.sqrt(clamp(num('eta')/100,.7,1)),bDroop:(num('bDroop')||3)/100,Hb:num('Hb')||6,socTarget:num('socTarget')/100,socLow:num('socLow')/100,socHigh:num('socHigh')/100,gridMW:num('gridMW'),gridImport:num('gridImport'),gridExport:num('gridExport'),islandable:$('islandable').checked,qMax:num('qMax'),qDroop:num('qDroop')||.04,uf1:num('uf1'),uf2:num('uf2'),uf3:num('uf3'),rocofTrip:num('rocofTrip')||1.5,dieselPrice:num('dieselPrice')||1.2};}
function validate(){const x=input(),e=[],w=[];if(x.dt<.05||x.dt>2)e.push('时间步必须在0.05–2秒之间');if(x.load<=0)e.push('基准负荷必须大于0');if(x.loadVar>x.load*.6)w.push('负荷波动幅值超过基准负荷60%，请确认工艺合理性');if(x.bP<0||x.bE<0)e.push('BESS功率与容量不能为负');if(x.bP>0&&x.bE/x.bP<.25)w.push('BESS持续时间低于0.25小时，仅适合短时支撑');if(!(x.socLow<x.socTarget&&x.socTarget<x.socHigh))e.push('SOC下限、目标、上限必须依次递增');if(!(x.uf1>x.uf2&&x.uf2>x.uf3))e.push('UFLS阈值必须依次下降');if(mode==='offgrid'&&x.dg33+x.dg12===0&&x.bP===0)e.push('离网模式必须至少有柴油机或BESS成网电源');if(mode!=='offgrid'&&x.gridMW<=0)e.push('并网/混合模式必须设置电网容量');if(x.gridImport>x.gridMW)w.push('PCC进口上限高于电网容量，将按电网容量限制');if(x.gridExport>x.gridMW)w.push('PCC反送上限高于电网容量，将按电网容量限制');$('validation').innerHTML=[...e.map(v=>`<div class="err">✕ ${v}</div>`),...w.map(v=>`<div class="warn">△ ${v}</div>`),...(e.length?[]:[`<div class="ok">✓ 参数逻辑检查通过</div>`])].join('');return{ok:!e.length,e,w,x};}
function makeGen(cap,type,on,x){const p0=on?cap*x.minLoad:0;return{cap,type,online:on,state:on?'RUNNING':'OFF',P:p0,Pcmd:p0,Pgov:p0,Pmech:p0,start:0,stopTimer:0,cool:0,Tg:.35,Te:1.8,H:4};}
function makeFleet(x){const f=[];for(let i=0;i<6;i++)f.push(makeGen(3.3,'3.3MW',i<x.dg33,x));for(let i=0;i<2;i++)f.push(makeGen(1.25,'1.25MW',i<x.dg12,x));return f;}
function processInit(x){return{noise:0,crusher:0,mill:.92,pumps:.7,conveyor:.55,shift:0,nextMotor:x.motorInt*(.75+.5*rng()),motorT:0,motorDur:0};}
function init(){const v=validate();if(!v.ok)return false;seed=42;const x=v.x;S={x,t:0,T:x.hours*3600,f:x.f0,fGrid:x.f0,dfdt:0,fMeas:x.f0,V:1,Q:0,E:x.bE*x.soc0,bPwr:0,bCmd:0,bFilt:0,pv:0,wind:0,grid:0,gridAvailable:mode!=='offgrid',pccClosed:mode!=='offgrid',fleet:makeFleet(x),proc:processInit(x),uf:[{f:x.uf1,s:.10,a:false,t:0},{f:x.uf2,s:.20,a:false,t:0},{f:x.uf3,s:.25,a:false,t:0}],shed:0,fuel:0,baseFuel:0,loadE:0,reToLoadE:0,curtE:0,unservedE:0,fmin:x.f0,fmax:x.f0,rocof:0,vmin:1,vmax:1,n1:true,fast10:0,spin60:0,start10:0,black:'',blackTimer:0,faultPVUntil:0,pvScale:1,powerResidual:0,powerResidualMax:0,activeFaults:new Map(),nextSample:0};series=[];events=[];started=true;setUI('PAUSED');$('log').textContent='[Ready] V6.1 physics-correction model initialized.';document.title='矿山微电网仿真与配置优化 · EnergizeOS · V6.1';const sub=document.querySelector('.brand small');if(sub)sub.textContent='V6.1 · Physics-Corrected Dynamic Model';update();draw();return true;}
function solarAvailable(t,x){const h=(t/3600)%24;if(h<5.7||h>18.3)return 0;const sun=Math.sin(Math.PI*(h-5.7)/12.6);const cloud=clamp(1-x.cloud*(.22+.28*Math.sin(t/83)+.18*Math.sin(t/19)),.08,1);return x.pvMax*Math.pow(Math.max(0,sun),1.45)*cloud*S.pvScale;}
function windAvailable(t,x){const gust=.11*Math.sin(t/71)+.06*Math.sin(t/17)+.025*normal();const v=Math.max(0,x.windMean*(1+gust));if(v<3)return 0;if(v<12)return x.windMax*Math.pow((v-3)/9,3);if(v<=25)return x.windMax;return 0;}
function ramp(target,current,rate,pmax,dt){const d=Math.max(0,rate)*Math.max(pmax,0)*dt;return clamp(target,current-d,current+d);}
function processLoad(dt){const x=S.x,p=S.proc,h=(S.t/3600)%24;const shiftTarget=(h>=6&&h<14)?1:(h>=14&&h<22)?.96:.9;p.shift=firstOrder(p.shift,shiftTarget,900,dt);p.noise=clamp(.985*p.noise+.12*normal()*Math.sqrt(dt),-1,1);p.crusher=firstOrder(p.crusher,.55+.35*(Math.sin(S.t/430)>-.35?1:0),25,dt);p.mill=firstOrder(p.mill,.9+.06*Math.sin(S.t/1100),120,dt);p.pumps=firstOrder(p.pumps,.65+.16*Math.sin(S.t/780+1.2),80,dt);p.conveyor=firstOrder(p.conveyor,.5+.28*(Math.sin(S.t/260)>0?1:0),18,dt);if(S.t>=p.nextMotor&&p.motorT<=0){p.motorDur=8+4*rng();p.motorT=p.motorDur;p.nextMotor=S.t+x.motorInt*(.75+.5*rng());events.push({t:S.t,type:'MOTOR_START'});log(`${ts(S.t)} motor start event`);}let motorP=0,motorQ=0;if(p.motorT>0){const elapsed=p.motorDur-p.motorT;motorP=x.motorMW*(.18+.82*Math.exp(-elapsed/2.2));motorQ=x.motorMW*(.35+2.6*Math.exp(-elapsed/1.5));p.motorT=Math.max(0,p.motorT-dt);}const mix=.34*p.mill+.22*p.crusher+.18*p.pumps+.16*p.conveyor+.10;const base=x.load*p.shift*(.82+.18*mix);const variability=x.loadVar*(.55*p.noise+.25*Math.sin(S.t/1700)+.2*Math.sin(S.t/310));return{P:Math.max(.15*x.load,base+variability+motorP),Qmotor:motorQ};}
function applyUFLS(f,dt){for(const q of S.uf){if(!q.a&&f<=q.f){q.t+=dt;if(q.t>=.15){q.a=true;events.push({t:S.t,type:'UFLS',threshold:q.f});log(`${ts(S.t)} UFLS ${q.f.toFixed(1)} Hz`);}}else if(q.a&&f>q.f+.25){q.a=false;q.t=0;}else if(!q.a)q.t=Math.max(0,q.t-dt*2);}S.shed=clamp(S.uf.filter(q=>q.a).reduce((a,q)=>a+q.s,0),0,.65);}
function sfc(pu){if(pu<=0)return 0;if(pu<.25)return lerp(420,325,pu/.25);if(pu<.5)return lerp(325,255,(pu-.25)/.25);if(pu<.75)return lerp(255,225,(pu-.5)/.25);return lerp(225,218,(pu-.75)/.25);}
function fuelRate(P,cap){return P>0?(sfc(clamp(P/cap,0,1))/1000)*(P*1000)/.84:0;}
function scheduleDG(target,dt,connected){const x=S.x;for(const g of S.fleet){if(g.cool>0)g.cool=Math.max(0,g.cool-dt);if(g.state==='STARTING'){g.start-=dt;if(g.start<=0){g.state='RUNNING';g.online=true;g.P=g.Pgov=g.Pmech=g.cap*x.minLoad;log(`${ts(S.t)} ${g.type} synchronized`);}}}const running=S.fleet.filter(g=>g.online),cap=running.reduce((a,g)=>a+g.cap,0),min=running.reduce((a,g)=>a+g.cap*x.minLoad,0);if(target>cap*.84){const g=S.fleet.find(q=>q.state==='OFF'&&q.cool<=0);if(g){g.state='STARTING';g.start=x.startDelay;log(`${ts(S.t)} start request ${g.type}`);}}if(connected&&target<Math.max(0,min*.35)){for(const g of [...running].reverse()){g.stopTimer+=dt;if(g.stopTimer>300&&running.length>1){g.online=false;g.state='OFF';g.P=g.Pgov=g.Pmech=0;g.cool=300;log(`${ts(S.t)} ${g.type} stopped on low demand`);break;}}}else running.forEach(g=>g.stopTimer=0);const run=S.fleet.filter(g=>g.online),runCap=run.reduce((a,g)=>a+g.cap,0),runMin=run.reduce((a,g)=>a+g.cap*x.minLoad,0),dispatch=runCap?clamp(target,connected?0:runMin,runCap):0;for(const g of run){const share=runCap?dispatch*g.cap/runCap:0;g.Pcmd=connected?clamp(share,0,g.cap):clamp(share,g.cap*x.minLoad,g.cap);const freqBias=connected?0:-(S.fMeas-x.f0)/Math.max(.001,x.droop)*g.cap;const govTarget=clamp(g.Pcmd+freqBias,connected?0:g.cap*x.minLoad,g.cap);g.Pgov=firstOrder(g.Pgov,govTarget,g.Tg,dt);g.Pmech=firstOrder(g.Pmech,g.Pgov,g.Te,dt);const rr=g.Pmech>g.P?x.rampUp:x.rampDn;g.P=ramp(g.Pmech,g.P,rr,g.cap,dt);}return S.fleet.reduce((a,g)=>a+(g.online?g.P:0),0);}
function baselineFuel(load,x){const units=[3.3,3.3,3.3,3.3,3.3,3.3,1.25,1.25];let chosen=[],cap=0;for(const c of units){chosen.push(c);cap+=c;if(cap>=load*1.15)break;}if(!chosen.length)return 0;const min=chosen.reduce((a,c)=>a+c*x.minLoad,0),target=clamp(load,min,cap),pu=target/cap;return chosen.reduce((a,c)=>a+fuelRate(c*pu,c),0);}
function bessLimits(){const x=S.x,soc=x.bE?S.E/x.bE:0;let dis=x.bP,chg=x.bP;if(soc<=x.socLow)dis*=clamp((soc-.05)/Math.max(.01,x.socLow-.05),0,1);if(soc>=x.socHigh)chg*=clamp((.98-soc)/Math.max(.01,.98-x.socHigh),0,1);return{soc,dis,chg};}
function bessControl(netBeforeBess,dt,connected){const x=S.x;if(x.bP<=0||x.bE<=0){S.bPwr=0;return 0;}const L=bessLimits();S.fMeas=firstOrder(S.fMeas,S.f,.15,dt);const df=S.fMeas-x.f0,dead=.03,fErr=Math.abs(df)>dead?df-Math.sign(df)*dead:0;let target=0;if(connected){const peakTarget=Math.min(x.gridImport||x.gridMW,Math.max(0,x.load*.78));const expectedGrid=-netBeforeBess,shave=Math.max(0,expectedGrid-peakTarget),absorb=Math.max(0,-expectedGrid-Math.min(x.gridExport,x.gridMW)),socTerm=(L.soc-x.socTarget)*x.bP*.18;target=shave-absorb+socTerm-(fErr/Math.max(.001,x.bDroop))*x.bP*.08;}else{const balance=-netBeforeBess,droop=-(fErr/Math.max(.001,x.bDroop))*x.bP,inertia=-(2*x.Hb*x.bP/x.f0)*S.dfdt,socTerm=(L.soc-x.socTarget)*x.bP*.12;target=.58*balance+.26*droop+.10*inertia+.06*socTerm;}target=clamp(target,-L.chg,L.dis);S.bCmd=target;S.bFilt=firstOrder(S.bFilt,S.bCmd,.12,dt);S.bPwr=ramp(S.bFilt,S.bPwr,2.5,x.bP,dt);return S.bPwr;}
function gridFrequency(dt){const x=S.x;S.fGrid=x.f0+.015*Math.sin(S.t/420)+.006*Math.sin(S.t/37);const old=S.f;S.f=firstOrder(S.f,S.fGrid,.3,dt);S.dfdt=(S.f-old)/Math.max(dt,.001);}
function islandFrequency(imbalance,dt){const x=S.x,run=S.fleet.filter(g=>g.online),Sbase=Math.max(x.load,run.reduce((a,g)=>a+g.cap,0),1),Heq=Math.max(.4,run.reduce((a,g)=>a+g.H*g.cap,0)/Sbase+(x.bP>0?x.Hb*x.bP/Sbase:0)),D=1.8*Sbase,damping=-D*(S.f-x.f0)/x.f0;let dfd=x.f0*(imbalance+damping)/(2*Heq*Sbase);if(!Number.isFinite(dfd))dfd=0;S.dfdt=clamp(dfd,-8,8);S.f+=S.dfdt*dt;}
function voltageModel(Pload,Qmotor,dg,bp,connected,dt){const x=S.x,qLoad=Pload*.22+Qmotor,smax=Math.max(x.bP,x.qMax),qCap=Math.min(x.qMax,Math.sqrt(Math.max(0,smax*smax-bp*bp))),qpcs=clamp((1-S.V)/Math.max(.01,x.qDroop)*qCap,-qCap,qCap),qDG=dg*.16;S.Q=qpcs+qDG-qLoad;const stiffness=connected?28:8,target=1+S.Q/Math.max(Pload,1)/stiffness;S.V=firstOrder(S.V,clamp(target,.78,1.12),connected?.25:1.8,dt);}
function opState(){if(S.black)return S.black;if(S.gridAvailable&&S.pccClosed)return mode==='gridtied'?'GRID-TIED':'HYBRID';const dg=S.fleet.some(g=>g.online),soc=S.x.bE?S.E/S.x.bE:0;if(dg&&S.x.bP>0)return'DG+BESS ISLAND';if(dg)return'DG-FORMING';if(S.x.bP>0&&soc>.2)return'BESS-FORMING';return'BLACKOUT';}
function blackStep(dt){if(!S.black)return;S.blackTimer-=dt;if(S.black==='BLACK START: DC/UPS'&&S.blackTimer<=0){S.black='BLACK START: ENERGIZE BUS';S.blackTimer=10;log(`${ts(S.t)} energize MV bus`);}else if(S.black==='BLACK START: ENERGIZE BUS'&&S.blackTimer<=0){S.black='BLACK START: START DG';const g=S.fleet[0];if(g){g.state='STARTING';g.start=S.x.startDelay;}log(`${ts(S.t)} black-start DG request`);}else if(S.black==='BLACK START: START DG'&&S.fleet.some(g=>g.online)){S.black='';log(`${ts(S.t)} black-start sequence complete`);}}
function step(){const x=S.x,dt=x.dt;S.t+=dt;if(S.faultPVUntil&&S.t>=S.faultPVUntil){S.pvScale=1;S.faultPVUntil=0;S.activeFaults.delete('pv');log(`${ts(S.t)} PV cloud cleared`);}const load=processLoad(dt);applyUFLS(S.f,dt);const rawLoad=load.P,served=rawLoad*(1-S.shed),pvAv=solarAvailable(S.t,x),windAv=windAvailable(S.t,x);S.pv=ramp(pvAv,S.pv,.018,x.pvMax,dt);S.wind=ramp(windAv,S.wind,.012,x.windMax,dt);const connected=S.gridAvailable&&S.pccClosed;let dgTarget;if(connected){const net=Math.max(0,served-S.pv-S.wind);dgTarget=mode==='hybrid'?Math.max(0,net-Math.min(x.gridImport,x.gridMW)*.65):Math.max(0,net-Math.min(x.gridImport,x.gridMW));}else dgTarget=Math.max(0,served-S.pv-S.wind-S.bPwr);const dg=scheduleDG(dgTarget,dt,connected);let pre=dg+S.pv+S.wind-served,bp=bessControl(pre,dt,connected),grid=0;if(connected){const residual=served-(dg+S.pv+S.wind+bp);grid=clamp(residual,-Math.min(x.gridExport,x.gridMW),Math.min(x.gridImport||x.gridMW,x.gridMW));const after=dg+S.pv+S.wind+bp+grid-served;if(Math.abs(after)>.02)bp=bessControl(dg+S.pv+S.wind+grid-served,dt,connected);}S.grid=grid;const supply=dg+S.pv+S.wind+bp+grid,imbalance=supply-served;S.powerResidual=imbalance;S.powerResidualMax=Math.max(S.powerResidualMax,Math.abs(imbalance));if(connected)gridFrequency(dt);else islandFrequency(imbalance,dt);voltageModel(served,load.Qmotor,dg,bp,connected,dt);const deficit=Math.max(0,-imbalance);S.unservedE+=(deficit+rawLoad*S.shed)*dt/3600;S.reToLoadE+=Math.min(served,Math.max(0,S.pv+S.wind))*dt/3600;S.loadE+=rawLoad*dt/3600;S.curtE+=(Math.max(0,pvAv-S.pv)+Math.max(0,windAv-S.wind))*dt/3600;if(x.bE>0)S.E=clamp(S.E-(bp>0?bp/x.eta:bp*x.eta)*dt/3600,0,x.bE);S.fuel+=S.fleet.reduce((a,g)=>a+(g.online?fuelRate(g.P,g.cap):0),0)*dt/3600;S.baseFuel+=baselineFuel(rawLoad,x)*dt/3600;const online=S.fleet.filter(g=>g.online),onlineCap=online.reduce((a,g)=>a+g.cap,0),largest=Math.max(0,...online.map(g=>g.cap)),remain=Math.max(0,onlineCap-largest),bAvail=Math.min(x.bP,Math.max(0,(S.E-x.bE*.2)*3600/60));S.fast10=online.reduce((a,g)=>a+Math.min(g.cap-g.P,x.rampUp*10),0)+Math.min(bAvail,x.bP);S.spin60=online.reduce((a,g)=>a+Math.min(g.cap-g.P,x.rampUp*60),0)+bAvail;S.start10=S.fleet.filter(g=>!g.online&&g.cool<=0&&x.startDelay<=600).reduce((a,g)=>a+g.cap,0);S.n1=remain+bAvail+(connected?Math.min(x.gridMW,x.gridImport):0)>=rawLoad*1.1;S.fmin=Math.min(S.fmin,S.f);S.fmax=Math.max(S.fmax,S.f);S.rocof=Math.max(S.rocof,Math.abs(S.dfdt));S.vmin=Math.min(S.vmin,S.V);S.vmax=Math.max(S.vmax,S.V);if(Math.abs(S.dfdt)>x.rocofTrip&&(!events.length||events.at(-1).type!=='ROCOF_EXCEED'||S.t-events.at(-1).t>5))events.push({t:S.t,type:'ROCOF_EXCEED',value:S.dfdt});blackStep(dt);S.op=opState();if(S.t>=S.nextSample){series.push({t:S.t,pv:S.pv,wind:S.wind,dg,b:bp,grid:S.grid,Sload:served,f:S.f,df:S.f-x.f0,soc:x.bE?100*S.E/x.bE:0,V:S.V,Q:S.Q,op:S.op});S.nextSample+=Math.max(2,S.T/12000);if(series.length>14000)series.shift();}}
function fault(type){if(ui!=='RUNNING')return;if(type==='dg'){const g=S.fleet.filter(q=>q.online).sort((a,b)=>b.cap-a.cap)[0];if(g){g.online=false;g.state='OFF';g.P=g.Pgov=g.Pmech=0;g.cool=300;events.push({t:S.t,type:'DG_TRIP'});S.activeFaults.set('dg','已触发');log(`${ts(S.t)} largest DG tripped`);}}if(type==='pv'&&!S.activeFaults.has('pv')){S.pvScale=.2;S.faultPVUntil=S.t+300;S.activeFaults.set('pv','300s');events.push({t:S.t,type:'PV_CLOUD'});log(`${ts(S.t)} PV cloud event`);}if(type==='grid'&&S.gridAvailable){S.gridAvailable=false;S.pccClosed=false;S.activeFaults.set('grid','失电');events.push({t:S.t,type:'GRID_LOSS'});if(!S.x.islandable){S.fleet.forEach(g=>{g.online=false;g.state='OFF';g.P=0;});log(`${ts(S.t)} grid loss — islanding not permitted`);}else log(`${ts(S.t)} grid loss — island transition`);}if(type==='black'&&!S.black){S.gridAvailable=false;S.pccClosed=false;S.fleet.forEach(g=>{g.online=false;g.state='OFF';g.P=0;g.start=0;});S.black='BLACK START: DC/UPS';S.blackTimer=5;S.activeFaults.set('black','进行中');events.push({t:S.t,type:'BLACK_START'});log(`${ts(S.t)} black-start sequence initiated`);}updateButtons();}
function setK(id,v,c=''){const e=$(id);e.className='kpi '+c;e.querySelector('b').textContent=v;}
function update(){if(!started)return;const x=S.x,soc=x.bE?100*S.E/x.bE:0,saved=Math.max(0,S.baseFuel-S.fuel),re=S.loadE?100*S.reToLoadE/S.loadE:0;setK('kFuel',`${S.fuel.toFixed(0)} L`);setK('kSave',`${saved.toFixed(0)} L`,saved>0?'ok':'');setK('kRE',`${re.toFixed(1)}%`,re>40?'ok':'');setK('kCurt',`${S.curtE.toFixed(2)} MWh`,S.curtE>1?'warn':'');setK('kFreq',`${S.fmin.toFixed(2)}/${S.fmax.toFixed(2)}`,S.fmin<S.x.uf1?'bad':'ok');setK('kRo',`${S.rocof.toFixed(2)} Hz/s`,S.rocof>S.x.rocofTrip?'bad':'');setK('kSOC',`${soc.toFixed(1)}%`,soc<20?'bad':soc<30?'warn':'ok');setK('kEENS',`${S.unservedE.toFixed(3)} MWh`,S.unservedE>0?'bad':'ok');$('bMode').textContent=S.op;$('bFreq').textContent=`${S.f.toFixed(3)} Hz`;$('bRun').textContent=ui;$('bRun').className='badge '+(ui==='RUNNING'?'ok':ui==='PAUSED'?'warn':'');$('pills').innerHTML=`<span class="pill ${S.n1?'ok':'bad'}">Gen N-1 ${S.n1?'OK':'FAIL'}</span><span class="pill ${Math.abs(S.f-x.f0)<.3?'ok':'bad'}">Δf ${(S.f-x.f0).toFixed(3)} Hz</span><span class="pill ${S.V>.9&&S.V<1.1?'ok':'bad'}">V ${S.V.toFixed(3)} pu</span><span class="pill">F10 ${S.fast10.toFixed(1)} MW</span><span class="pill">S60 ${S.spin60.toFixed(1)} MW</span><span class="pill">Start10 ${S.start10.toFixed(1)} MW</span><span class="pill ${Math.abs(S.powerResidual)<.05?'ok':'bad'}">Residual ${S.powerResidual.toFixed(3)} MW</span>`;updateSLD();updateButtons();}
function plot(id,keys,colors){const c=$(id),r=c.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);c.width=Math.max(2,r.width*dpr);c.height=Math.max(2,r.height*dpr);const g=c.getContext('2d'),w=c.width,h=c.height;g.fillStyle='#fff';g.fillRect(0,0,w,h);if(series.length<2)return;const ml=42*dpr,mr=10*dpr,mt=10*dpr,mb=18*dpr,t0=series[0].t,t1=series.at(-1).t,vals=keys.flatMap(k=>series.map(d=>d[k]));let mn=Math.min(...vals),mx=Math.max(...vals);if(mn===mx){mn-=1;mx+=1;}if(keys.includes('f')){mn=Math.min(mn,S.x.f0-.8);mx=Math.max(mx,S.x.f0+.8);}const X=t=>ml+(w-ml-mr)*(t-t0)/Math.max(1,t1-t0),Y=v=>mt+(h-mt-mb)*(1-(v-mn)/(mx-mn));g.strokeStyle='#E5E9EE';for(let i=0;i<5;i++){const y=mt+(h-mt-mb)*i/4;g.beginPath();g.moveTo(ml,y);g.lineTo(w-mr,y);g.stroke();}keys.forEach((k,j)=>{g.beginPath();series.forEach((d,i)=>{const x=X(d.t),y=Y(d[k]);i?g.lineTo(x,y):g.moveTo(x,y);});g.strokeStyle=colors[j];g.lineWidth=(j===0?2.2:1.6)*dpr;g.stroke();});}
function draw(){plot('pChart',['Sload','dg','pv','wind','b','grid'],['#64748B','#7C3AED','#D4840A','#0EA5E9','#16A34A','#8B5CF6']);plot('fChart',['f'],['#C026D3']);plot('vChart',['V'],['#B45309']);plot('qChart',['Q'],['#3B82F6']);}
function updateSLD(){const map={sldGrid:S.gridAvailable&&S.pccClosed,sldDG:S.fleet.some(g=>g.online),sldBESS:S.x.bP>0,sldPV:S.pv>0,sldWind:S.wind>0};for(const[k,v]of Object.entries(map))$(k).style.opacity=v?1:.2;$('sldText').textContent=`${S.op} · f ${S.f.toFixed(3)} Hz · V ${S.V.toFixed(3)} pu · SOC ${(S.x.bE?100*S.E/S.x.bE:0).toFixed(1)}%`;}
function setUI(state){ui=state;running=state==='RUNNING';updateButtons();}
function updateButtons(){const start=$('start'),pause=$('pause'),reset=$('reset'),exp=$('export'),faults=[...document.querySelectorAll('[data-fault]')];start.disabled=ui==='RUNNING'||ui==='COMPLETE';pause.disabled=ui!=='RUNNING';reset.disabled=false;exp.disabled=!started;start.textContent=ui==='PAUSED'&&started?'继续':ui==='RUNNING'?'运行中':ui==='COMPLETE'?'已完成':'启动';pause.textContent=ui==='RUNNING'?'暂停':'已暂停';start.className='btn '+((ui==='IDLE'||ui==='PAUSED')?'primary':'');pause.className='btn '+(ui==='RUNNING'?'primary':'');reset.className='btn '+(ui==='COMPLETE'?'primary':'');faults.forEach(b=>{const active=S.activeFaults?.has(b.dataset.fault);b.disabled=ui!=='RUNNING'||active;b.className='btn fault'+(active?' active':'');b.style.background=active?'#FEE2E2':'';});}
function loop(){if(ui!=='RUNNING')return;const n=Math.max(1,Math.round(8/S.x.dt));for(let i=0;i<n&&S.t<S.T;i++)step();update();draw();if(S.t>=S.T){setUI('COMPLETE');log(`${ts(S.t)} simulation complete`);return;}raf=requestAnimationFrame(loop);}
function exportJSON(){if(!started)return;const out={modelVersion:VERSION,build:BUILD,generatedAt:new Date().toISOString(),scope:'Conceptual RMS-style dynamic screening; not load-flow, short-circuit, EMT, protection coordination or detailed engineering.',inputs:S.x,mode,kpis:{fuel_L:S.fuel,fuelSavedBaseline_L:Math.max(0,S.baseFuel-S.fuel),renewableToLoad_pct:S.loadE?100*S.reToLoadE/S.loadE:0,curtailment_MWh:S.curtE,EENS_MWh:S.unservedE,fMin_Hz:S.fmin,fMax_Hz:S.fmax,rocofPeak_Hzs:S.rocof,Vmin_pu:S.vmin,Vmax_pu:S.vmax,finalSOC_pct:S.x.bE?100*S.E/S.x.bE:0,generationN1:S.n1,maxInstantaneousPowerResidual_MW:S.powerResidualMax},events,timeseries:series};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:'application/json'}));a.download=`energize-mine-sim-v6-1-${Date.now()}.json`;a.click();}
function bind(){document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{if(ui==='RUNNING')return;document.querySelectorAll('.tab').forEach(q=>q.classList.remove('active'));t.classList.add('active');mode=t.dataset.mode;$('gridGroup').style.display=mode==='offgrid'?'none':'block';validate();});document.querySelectorAll('input,select').forEach(e=>e.addEventListener('change',()=>{if(ui!=='RUNNING')validate();}));$('start').onclick=()=>{if(!started&&!init())return;setUI('RUNNING');cancelAnimationFrame(raf);loop();};$('pause').onclick=()=>{setUI('PAUSED');cancelAnimationFrame(raf);update();};$('reset').onclick=()=>{cancelAnimationFrame(raf);running=false;started=false;S={};series=[];events=[];setUI('IDLE');$('log').textContent='[Idle] 参数保留，点击启动创建新仿真。';document.querySelectorAll('.kpi b').forEach(b=>b.textContent='—');$('pills').innerHTML='';draw();};$('export').onclick=exportJSON;document.querySelectorAll('[data-fault]').forEach(b=>b.onclick=()=>fault(b.dataset.fault));window.addEventListener('resize',()=>started&&draw());setUI('IDLE');validate();}
document.addEventListener('DOMContentLoaded',bind);
})();